### ISSUE TITLE
The version 9a6d6c4 for this integration can not be used with HACS

### ISSUE THREAD

**Issue by bruvv** [HAEdwin/homeassistant-apsystems_ecu_proxy#1]
When running the latest version of HACS Integration version: 2.0.0 and Frontend version: 20240814080035 I get the following error when trying to download/install this:
<img width="534" alt="image" src="https://github.com/user-attachments/assets/98c99b7c-32f9-46b6-96e8-458414b056e7">

**Comment by HAEdwin** [comment]
The integration was not made HACS ready yet. Try the following if you do not receive an update notice yet:
In HA choose HACS in the left menu. Under "Pending update" choose this integration and at the end of the line select the three dots. Choose "Redownload", choose "Need a different version?" and select the Release. Finally choose "Download".

**Comment by HAEdwin** [comment]
Should be solved by now. Latest release is v0.2.3. I'll close this issue, feel free to open a new one if needed.
