### ISSUE TITLE
no_update_timeout - 'NoneType' passed as argument to int()

### ISSUE THREAD

**Issue by machadolucas** [HAEdwin/homeassistant-apsystems_ecu_proxy#11]
**Describe the bug**
After updating to version v1.1.0, I got the following error in the logs and the integration does not load anymore. I have tried to reload it but nothing changes.

```
Error setting up entry APsystems ECU Proxy for apsystems_ecu_proxy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/apsystems_ecu_proxy/__init__.py", line 40, in async_setup_entry
    api_handler = APIManager(hass, config_entry)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/apsystems_ecu_proxy/__init__.py", line 102, in __init__
    self.no_update_timeout = int(self.config_entry.data.get("no_update_timeout"))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Hard- and Software:**
 - ECU type: ECU-R 2160
 - Integration version:  v1.1.0
 - Home Assistant version: 2024.11.1

**Comment by HAEdwin** [comment]
You are absolutely right, the config_flow was still in development and I did not think about migration for existing users - there were no signals from Home Assistant Analytics that there are already users! Great that you're using the integration at this early stage and thank you for your comments so that I learn to improve myself in my hobby.
